# Generated by Django 4.2.2 on 2023-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stafftimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phno', models.CharField(max_length=10, null=True)),
                ('uname', models.CharField(max_length=15, null=True)),
                ('pword', models.CharField(max_length=8, null=True)),
                ('dep', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
