# Generated by Django 4.2.2 on 2023-06-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staffregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.TextField()),
                ('topics', models.TextField()),
                ('absentees', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
