# Generated by Django 4.2.2 on 2023-06-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='absentees',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
