# Generated by Django 4.2.2 on 2023-06-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_assignments_absentees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
