# Generated by Django 4.2.2 on 2023-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_stafftimetable_delete_studenttimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hour', models.TextField()),
                ('second_hour', models.TextField()),
                ('third_hour', models.TextField()),
                ('fourth_hour', models.TextField()),
            ],
        ),
    ]
