# Generated by Django 4.2.2 on 2023-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='subcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
