# Generated by Django 4.2.3 on 2023-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_timetable_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subcode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
