# Generated by Django 4.2.3 on 2023-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_timetable_fname_timetable_subcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='first_hour',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourth_hour',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_hour',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_hour',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
