# Generated by Django 4.2.3 on 2023-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_timetable_date_alter_timetable_first_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='first_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourth_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_hour',
            field=models.IntegerField(default=0),
        ),
    ]
