# Generated by Django 4.2.3 on 2023-08-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_timetable_first_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subcode',
        ),
    ]
